name: SonarCloud analysis
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  pull-requests: read 
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args:
            -Dsonar.projectKey=Exarilo_Flow.Launcher.Plugin.LinkOpener
            -Dsonar.organization=exarilo
          projectBaseDir: .
      - name: Get SonarCloud analysis results
        run: |
          sleep 10  
          curl -u ${{ secrets.SONAR_TOKEN }}: \
          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Exarilo_Flow.Launcher.Plugin.LinkOpener" \
          -o analysis_result.json
          cat analysis_result.json  
      - name: Send webhook to Discord
        run: |
          analysis_status=$(jq -r '.projectStatus.status // "Unknown"' analysis_result.json)
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"SonarCloud analysis completed for project Exarilo_Flow.Launcher.Plugin.LinkOpener.\nStatus: ${analysis_status}\"}" \
          "${{ secrets.DISCORD_WEBHOOK }}"
